files: ^python/
fail_fast: true
repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 1.1.0
    hooks:
      - id: sync_with_poetry
        args: [--config=.pre-commit-config.yaml, --db=python/.conf/packages_list.json, python/poetry.lock]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-toml
        files: \.toml$
      - id: check-yaml
        files: \.yaml$
      - id: end-of-file-fixer
        files: \.py$
      - id: mixed-line-ending
        files: \.py$
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        files: \.py$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: local
    hooks:
    - id: mypy
      files: ^python/semantic_kernel/
      name: mypy
      entry: poetry -C python/ run python -m mypy -p semantic_kernel --config-file=python/mypy.ini
      language: system
      types: [python]
      pass_filenames: false
